# render.yaml
services:
  - type: web
    name: gas-station-pos
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /api/*
        destination: http://rpi.directvision.ru:4001/api/*